---
- hosts: jumpbox
  tasks:
  - name: Get openstack repo
    get_url:
      url: http://ctrl-79d3.rhpds.opentlc.com:/etc/yum.repos.d/open.repo
      dest: /etc/yum.repos.d/open.repo
  - name: Get openstack env 
    get_url:
      url: http://ctrl.example.com:/root/keystonerc_admin
      dest: /root/keystonerc_admin
  - name: Source keystone
    command: source /root/keystonerc_admin
  - name: Get openstack.pub
    get_url:
      url: http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
      dest: /tmp/openstack.pub
  - name: Get openstack to cloud-user
    command: cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
  - name: Install epel
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  - name: install openstack python
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - python
      - python-devel
      - python-pip
      - gcc
      - ansible
  - name: Install shade
    command: pip install shade

  - name: Make sure openstack folder
    file:
      path: /etc/openstack/
      state: directory
  - name: Get clouds.yaml
    copy:
      name: clouds.yaml
      dest:/ etc/openstack/

