---
- hosts: jumpbox
#  pre_tasks:
#  - name: Get openstack repo
#    get_url:
#      url: http://ctrl-12a5.rhpds.opentlc.com:/etc/yum.repos.d/open.repo
#      dest: /etc/yum.repos.d/open.repo
#  - name: Get openstack env
#    get_url:
#      url: http://ctrl.example.com:/root/keystonerc_admin
#      dest: /root/keystonerc_admin
#  - name: Source keystone
#    command: source /root/keystonerc_admin
#  - name: Get openstack.pub
#    get_url:
#      url: http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
#      dest: /tmp
#  - name: Get openstack to cloud-user
#    command: cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
#  - name: Install epel
#    yum:
#      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#  - name: install openstack python
#    yum:
#      name: "{{ item }}"
#      state: latest
#    with_items:
#      - python
#      - python-devel
#      - python-pip
#      - gcc
#      - ansible
#  - name: Install shade
#    command: pip install shade

  roles:
     - role: osp-network
     - role: osp-keypair
     - role: osp-security
     - role: osp-flavor
     - role: osp-servers
     - role: base-config
       tags: base-config


     - role: lb-tier
       tags: 
         - lbs
         - haproxy
 
 # Setup application servers tier
 
     - role: base-config
       tags: base-config
     - role: app-tier
       tags: 
         - apps
         - tomcat
 
 # Setup database tier
 
     - role: base-config
       tags: base-config
     - role: geerlingguy.postgresql
       tags: 
         - dbs
         - postgres
 
